final List<Map<String, dynamic>> dummyMenuList = [
  {
    'nama': 'Nasi Goreng',
    'jenis': 'Indonesian',
    'harga': 25000,
    'imageUrl': 'lib/assets/images/nasi_goreng.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Sate Ayam',
    'jenis': 'Indonesian',
    'harga': 30000,
    'imageUrl': 'lib/assets/images/sate_ayam.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Rendang',
    'jenis': 'Indonesian',
    'harga': 35000,
    'imageUrl': 'lib/assets/images/rendang.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Gado-gado',
    'jenis': 'Indonesian',
    'harga': 30.000,
    'imageUrl': 'lib/assets/images/gado_gado.jpeg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Soto Ayam',
    'jenis': 'Traditional',
    'harga': 22.000,
    'imageUrl': 'lib/assets/images/soto_ayam.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Bakso',
    'jenis': 'Traditional',
    'harga': 18.000,
    'imageUrl': 'lib/assets/images/bakso.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Mie Goreng',
    'jenis': 'Indonesian',
    'harga': 23.000,
    'imageUrl': 'lib/assets/images/mie_goreng.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Ayam Goreng',
    'jenis': 'Traditional',
    'harga': 28.000,
    'imageUrl': 'lib/assets/images/ayam_goreng.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Pecel Lele',
    'jenis': 'Traditional',
    'harga': 25.000,
    'imageUrl': 'lib/assets/images/pecel_lele.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Bebek Goreng',
    'jenis': 'Traditional',
    'harga': 32.000,
    'imageUrl': 'lib/assets/images/bebek_goreng.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Nasi Padang',
    'jenis': 'Indonesian',
    'harga': 30.000,
    'imageUrl': 'lib/assets/images/nasi_padang.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Nasi Uduk',
    'jenis': 'Traditional',
    'harga': 15.000,
    'imageUrl': 'lib/assets/images/nasi_uduk.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Ketoprak',
    'jenis': 'Jakarta',
    'harga': 18.000,
    'imageUrl': 'lib/assets/images/ketoprak.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Siomay',
    'jenis': 'Indonesian',
    'harga': 20.000,
    'imageUrl': 'lib/assets/images/siomay.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Batagor',
    'jenis': 'Sundanese',
    'harga': 22.000,
    'imageUrl': 'lib/assets/images/batagor.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Tahu Telur',
    'jenis': 'Surabaya',
    'harga': 18.000,
    'imageUrl': 'lib/assets/images/Tahu_Telur.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Rawon',
    'jenis': 'East Javanese',
    'harga': 28.000,
    'imageUrl': 'lib/assets/images/rawon.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Lontong Sayur',
    'jenis': 'Traditional',
    'harga': 16.000,
    'imageUrl': 'lib/assets/images/lontong_sayur.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Nasi Goreng Bakso',
    'jenis': 'Indonesian',
    'harga': 30.000,
    'imageUrl': 'lib/assets/images/nasi_goreng_bakso.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Sop Buntut',
    'jenis': 'Indonesian',
    'harga': 45.000,
    'imageUrl': 'lib/assets/images/sop_buntut.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Ikan Bakar',
    'jenis': 'Seafood',
    'harga': 35.000,
    'imageUrl': 'lib/assets/images/ikan_bakar.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Bubur Ayam',
    'jenis': 'Traditional',
    'harga': 15.000,
    'imageUrl': 'lib/assets/images/Bubur_Ayam.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Soto Betawi',
    'jenis': 'Jakarta',
    'harga': 25.000,
    'imageUrl': 'lib/assets/images/soto_betawi.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Tempe Penyet',
    'jenis': 'Traditional',
    'harga': 15.000,
    'imageUrl': 'lib/assets/images/tempe_penyet.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Es Teh',
    'jenis': 'Traditional',
    'harga': 5000,
    'imageUrl': 'lib/assets/images/es_teh.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Es Jeruk',
    'jenis': 'Fresh',
    'harga': 8000,
    'imageUrl': 'lib/assets/images/es_jeruk.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Es Kopi',
    'jenis': 'Coffee',
    'harga': 15000,
    'imageUrl': 'lib/assets/images/es_kopi.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Jus Alpukat',
    'jenis': 'Fresh',
    'harga': 12000,
    'imageUrl': 'lib/assets/images/jus_alpukat.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Jus Mangga',
    'jenis': 'Fresh',
    'harga': 10000,
    'imageUrl': 'lib/assets/images/jus_mangga.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Es Cincau',
    'jenis': 'Traditional',
    'harga': 7000,
    'imageUrl': 'lib/assets/images/es_cincau.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Wedang Jahe',
    'jenis': 'Traditional',
    'harga': 8000,
    'imageUrl': 'lib/assets/images/wedang_jahe.jpeg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Thai Tea',
    'jenis': 'Fusion',
    'harga': 12000,
    'imageUrl': 'lib/assets/images/thai_tea.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Kopi Tubruk',
    'jenis': 'Coffee',
    'harga': 8000,
    'imageUrl': 'lib/assets/images/kopi_tubruk.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Es Cendol',
    'jenis': 'Traditional',
    'harga': 10000,
    'imageUrl': 'lib/assets/images/es_cendol.jpeg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Soda Gembira',
    'jenis': 'Modern',
    'harga': 12000,
    'imageUrl': 'lib/assets/images/soda_gembira.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Bandrek',
    'jenis': 'Traditional',
    'harga': 9000,
    'imageUrl': 'lib/assets/images/bandrek.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Bajigur',
    'jenis': 'Traditional',
    'harga': 9000,
    'imageUrl': 'lib/assets/images/bajigur.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Es Lemon Tea',
    'jenis': 'Fresh',
    'harga': 8000,
    'imageUrl': 'lib/assets/images/es_lemon_tea.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Matcha Latte',
    'jenis': 'Fusion',
    'harga': 18000,
    'imageUrl': 'lib/assets/images/Matcha_latte.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Teh Tarik',
    'jenis': 'Malaysian Fusion',
    'harga': 10000,
    'imageUrl': 'lib/assets/images/teh_tarik.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Sekoteng',
    'jenis': 'Traditional',
    'harga': 12000,
    'imageUrl': 'lib/assets/images/Sekoteng.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Bir Pletok',
    'jenis': 'Betawi',
    'harga': 10000,
    'imageUrl': 'lib/assets/images/bir_pletok.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Jus Strawberry',
    'jenis': 'Fresh',
    'harga': 10000,
    'imageUrl': 'lib/assets/images/jus_strawberry.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Es Doger',
    'jenis': 'Traditional',
    'harga': 15000,
    'imageUrl': 'lib/assets/images/es_doger.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Es Kelapa Muda',
    'jenis': 'Fresh',
    'harga': 12000,
    'imageUrl': 'lib/assets/images/es_kelapa_muda.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Kopi Susu Gula Aren',
    'jenis': 'Modern Coffee',
    'harga': 18000,
    'imageUrl': 'lib/assets/images/es_kopi_susu_gula_aren.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Wedang Uwuh',
    'jenis': 'Javanese',
    'harga': 10000,
    'imageUrl': 'lib/assets/images/wedang_uwuh.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Selendang Mayang',
    'jenis': 'Betawi',
    'harga': 12000,
    'imageUrl': 'lib/assets/images/selendang_mayang.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Es Campur',
    'jenis': 'Traditional',
    'harga': 15000,
    'imageUrl': 'lib/assets/images/Es_Campur.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Pisang Goreng',
    'jenis': 'Traditional',
    'harga': 10000,
    'imageUrl': 'lib/assets/images/Pisang_Goreng.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Klepon',
    'jenis': 'Traditional',
    'harga': 8000,
    'imageUrl': 'lib/assets/images/Klepon.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Es Krim',
    'jenis': 'Ice Cream',
    'harga': 12000,
    'imageUrl': 'lib/assets/images/es_krim.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Martabak Manis',
    'jenis': 'Traditional',
    'harga': 25000,
    'imageUrl': 'lib/assets/images/martabak_manis.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Kue Cubit',
    'jenis': 'Modern',
    'harga': 10000,
    'imageUrl': 'lib/assets/images/kue_cubit.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Bubur Sumsum',
    'jenis': 'Traditional',
    'harga': 8000,
    'imageUrl': 'lib/assets/images/Bubur_Sumsum.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Roti Bakar',
    'jenis': 'Modern',
    'harga': 12000,
    'imageUrl': 'lib/assets/images/roti_bakar.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Putu Ayu',
    'jenis': 'Traditional',
    'harga': 3000,
    'imageUrl': 'lib/assets/images/putu_ayu.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Lupis',
    'jenis': 'Traditional',
    'harga': 5000,
    'imageUrl': 'lib/assets/images/lupis.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Onde-onde',
    'jenis': 'Traditional',
    'harga': 3000,
    'imageUrl': 'lib/assets/images/onde-onde.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Kue Lapis',
    'jenis': 'Traditional',
    'harga': 15000,
    'imageUrl': 'lib/assets/images/kue_lapis.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Bika Ambon',
    'jenis': 'Traditional',
    'harga': 20000,
    'imageUrl': 'lib/assets/images/bika_ambon.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Poffertjes',
    'jenis': 'Fusion',
    'harga': 18000,
    'imageUrl': 'lib/assets/images/poffertjes.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Pancake Durian',
    'jenis': 'Fusion',
    'harga': 25000,
    'imageUrl': 'lib/assets/images/pancake_durian.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Serabi',
    'jenis': 'Traditional',
    'harga': 7000,
    'imageUrl': 'lib/assets/images/serabi.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Kue Cucur',
    'jenis': 'Traditional',
    'harga': 3000,
    'imageUrl': 'lib/assets/images/kue_cucur.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Kolak Pisang',
    'jenis': 'Traditional',
    'harga': 12000,
    'imageUrl': 'lib/assets/images/kolak_pisang.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Cenil',
    'jenis': 'Traditional',
    'harga': 8000,
    'imageUrl': 'lib/assets/images/cenil.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Es Dawet',
    'jenis': 'Traditional',
    'harga': 10000,
    'imageUrl': 'lib/assets/images/es_dawet.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Kastengel',
    'jenis': 'Dutch-Indonesian',
    'harga': 25000,
    'imageUrl': 'lib/assets/images/kastengel.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Nastar',
    'jenis': 'Dutch-Indonesian',
    'harga': 25000,
    'imageUrl': 'lib/assets/images/nastar.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Putu Mayang',
    'jenis': 'Traditional',
    'harga': 8000,
    'imageUrl': 'lib/assets/images/putu_mayang.jpg',
    'status': 'Tersedia',
  },
  {
    'nama': 'Es Tebu',
    'jenis': 'Traditional',
    'harga': 6000,
    'imageUrl': 'lib/assets/images/es_tebu.jpg',
    'status': 'Tersedia',
  },
];
